apiVersion: v1
kind: Pod
metadata:
  name: ex-for-sa
spec:
  serviceAccountName: foo
  automountServiceAccountToken: false
  containers:
    - name: sleep-com
      image: nginxdemos/hello
      ports:
        - containerPort: 80
      command: ["sleep", "9999999"]
